### ISSUE TITLE
rspecをgreen_dayコマンドから実行できるようにしたい。

### ISSUE THREAD

**Issue by ratovia** [QWYNG/green_day#17]
atcoderに関連する作業をすべてgreen_dayで完結できるようにしたい。
rspecコマンドはそのうちの一つ

`green_day rspec abc001 A`
と入力すれば
`rspec abc001/spec/A.rb`
が自動で走りテスト実行できるようにする。

**Comment by QWYNG** [comment]
rspecコマンド自体は導入しないつもりです！ ユーザーがタイプ’するコマンドが増えるだけなので。

**Comment by ratovia** [comment]
フィードバックありがとうございます！
確かに、タイプ数増えていますもんね。

`/spec/`という文字が省略できること以外に、
コンテスト時には
```
be green_day n abc001  (n: new)
be green_day r abc001 A (r: rspec)
```
と使用できていて、nとrを変化させるだけなのでとても便利です。(beはbundle execのalias)
将来提出コマンドも実装するとより鮮明に効果でると思っています。
```
be green_day n abc001
be green_day r abc001 A
be green_day s abc001 A (s: submit)
be green_day r abc001 B
be green_day s abc001 B
```

一旦は方針に従い、導入しない方針承知しました。
提出コマンドも導入されたor導入した際にまた検討をお願いいたします。

本件クローズでも可です。
